### ISSUE TITLE
Documents not being written to Firestore

### ISSUE THREAD

**Issue by psenechal** [jdgamble555/adv-firestore-functions#3]
Hello...I am very curious about this package, but cannot seem to get it to do anything other than log an event.

I am attempting a very simple index of the "name" field for a collection of records:
```
exports.vintnerIndex = functions.firestore.document('vintner/{id}').onWrite(async (change: any, context: any): Promise<any> => {
  if (await eventExists(context)) {
    return null;
  }

  const searchable = ['name'];
  searchable.forEach(async (field: string) => {
    await fullTextIndex(change, context, field);
  })

  return null;
});
```

I can see in the logs that the function is executing and my database has a record in the "_events" collection for the execution, however, nothing else is being written to the database. I believe I should be expecting a new collection named "_search" to be created with the index documents, but that is not occurring. Also, the original documents are not being updated with any indexing data...just the data I have changed to trigger the function to run.

Do you know what I might possibly be doing wrong? Thanks for your assistance.

**Comment by jdgamble555** [comment]
Did you import the package?  You will need:

```javascript
import { eventExists, fullTextIndex } from 'adv-firestore-functions';`
```
at the top of your cloud function, and also you must install the package.  If that doesn't work, check your function error logs and let me know what message you're getting.

**Comment by psenechal** [comment]
Yes...package is installed and imports are present.
There are no messages in the logs for that function. I even tried removing the eventExists code to make sure it wasn’t exiting out for some reason...still didn’t work and still nothing in the logs.
I did add a console.log() at the beginning of the method  to make sure the code was actually executing and my log statement did appear in the logs, so I’m confident the method is executing.

Thanks

**Comment by jdgamble555** [comment]
It is *almost* impossible for there not be a log.  Make sure you have firebase functions installed correctly.  At **firebase.com** login to your project, go to **functions** then click on **logs** and select **vintnerIndex** (your function name), and there should be a log... you can see:
  
https://github.com/jdgamble555/adv-firestore-functions/blob/master/src/shared/events.ts
  
https://github.com/jdgamble555/adv-firestore-functions/blob/master/src/shared/search.ts
  
You can read the source code to see the **console.log** functions are printing.  If it works, there should be two new collections created **_events** and **_search**, which means the function worked.

**Comment by psenechal** [comment]
Part of this was my misunderstanding...I thought that simply updating the document (any field) would trigger the indexing, however, after looking at the code you referenced, I see that you specifically have to update the field(s) being indexed to trigger the index function. After updating the 'name' field that I'm indexing, I finally got something in the logs which was an error "Cannot find module 'html-to-text'". I installed this package in my functions directory and it's now creating documents in a collection named _search.

YAY!

So now my next question...the documentation indicates that the 'foreign-keys-to-index' option should take an array of the field names I want to return. It appears that this has been configured to be a single string however, not an array. It looks like I can only return the 'id' and another field currently. Are there any plans to change this to allow returning more than just the id and one other field?

Thanks

**Comment by jdgamble555** [comment]
Yes, you can create a map (a string mapping to true), or an array.  Before arrays were available in firestore, people used maps.  So depending on your goals, both are available.  You can see the documentation:

https://www.npmjs.com/package/adv-firestore-functions

Generally speaking, like this:

```javascript
await fullTextIndex(change, context, field, foreign-keys, 'map');
```

or 

```javascript
await fullTextIndex(change, context, field, foreign-keys, 'array');
```

**Comment by ganmaazuma02** [comment]
Hi, I've also tried to setup the package accordingly and got the same issue. It created the '_events' collection but not the '_search' collection. I've also installed the 'html-to-text' package as shown in a previous error. Now, I got this new error message.

This is my firebase function, very much the same as above:
```
exports.indexVisitor = functions.region('asia-southeast2')
.firestore.document('visitors/{id}').onWrite(async (change: any, context: any): Promise<any> => {
  if (await eventExists(context)) {
    return null;
  }

  const searchable = ['name'];
  searchable.forEach(async (field: string) => {
    await fullTextIndex(change, context, field);
  })

  return null;
});
```

Here is the log from my firebase function as soon as I added a document with the name field:
```
Error: Value for argument "data" is not a valid Firestore document. Cannot use "undefined" as a Firestore value (found in field "id"). If you want to ignore undefined values, enable `ignoreUndefinedProperties`.
    at validateUserInput (/workspace/node_modules/@google-cloud/firestore/build/src/serializer.js:271:19)
    at Object.validateUserInput (/workspace/node_modules/@google-cloud/firestore/build/src/serializer.js:263:13)
    at validateDocumentData (/workspace/node_modules/@google-cloud/firestore/build/src/write-batch.js:621:18)
    at WriteBatch.set (/workspace/node_modules/@google-cloud/firestore/build/src/write-batch.js:254:9)
    at /workspace/node_modules/adv-firestore-functions/lib/shared/search.js:127:31
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/workspace/node_modules/adv-firestore-functions/lib/shared/search.js:104:24)
    at Generator.next (<anonymous>)
    at /workspace/node_modules/adv-firestore-functions/lib/shared/search.js:27:71
    at new Promise (<anonymous>) 


Error: Process exited with code 16
    at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:271:38)
    at process.emit (events.js:315:20)
    at process.EventEmitter.emit (domain.js:483:12)
    at process.exit (internal/process/per_thread.js:167:15)
    at Object.logAndSendError (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/logger.js:37:9)
    at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:268:22)
    at process.emit (events.js:315:20)
    at process.EventEmitter.emit (domain.js:483:12)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

**Comment by jdgamble555** [comment]
@psenechal and @ganmaazuma02 - The **html-to-text** was not listed as dependencies, so I fixed that.

I also updated the README for some more clarifications.

I was not automatically creating the **_search** collection, but it should be fixed in the latest version .  Let me know if you have any problems.

**Comment by ganmaazuma02** [comment]
@jdgamble555 I've updated to the latest version and still getting the same error message with no _search collection created.

**Comment by jdgamble555** [comment]
@ganmaazuma02 - Sorry about that.  Try it now and let me know if it works, should be fixed...

**Comment by jdgamble555** [comment]
I am closing this due to inaction... I tested this on my end, and is working.
